### ISSUE TITLE
Publish on npm?

### ISSUE THREAD

**Issue by rybesh** [kevinb7/functify#2]
Any chance you could publish this on npm? I'd like to use it. If you're not planning on maintaining it, no worries, I can just fork.

**Comment by kevinb7** [comment]
It's funny, I haven't had an opportunity to use it myself in any projects.  Let me know if you run into any issues.  I guess once it's in npm it'll be easier to incorporate into new projects.  I can definitely publish it on npm.  Should be able to get to it this afternoon.

**Comment by rybesh** [comment]
Great, thanks!

**Comment by kevinb7** [comment]
https://www.npmjs.com/package/functify

**Comment by kevinb7** [comment]
Can you send me a link to the project you're using it?  I'm curious to see how other people are using it.

**Comment by kevinb7** [comment]
Sorry, should've tested the package earlier.  I fixed a few issues with it and it should be working now.

**Comment by rybesh** [comment]
Thanks for packaging! You can see how I'm using it here:

https://github.com/contours/react-transcript-player/blob/pagination/src/transcript.jsx#L51-L54
https://github.com/contours/react-transcript-player/blob/pagination/src/itertools.js

Note that I had to add a dependency on `babel-runtime` to get this to work for me; I'll send a pull request with what I had to change in `package.json`.

**Comment by kevinb7** [comment]
Cool.  Looking forward to the pull request.

I like what you did in itertools.js.  I made ```range``` a static method defined on ```functify``` so you can do:
```
let f = require('functify');
for (let i in f.range(0,10)) {
    ...
}
```
I can see how ```enumerate``` would be quite useful.  It'd probably be more efficient to define without using ```zip```.

**Comment by rybesh** [comment]
Yeah, the reason I defined a new range function was because I wanted to support infinite ranges; so `range(5)` means `[5,∞)` rather than `[0,5)`. That's useful for zipping with a generator of indeterminate length to enumerate it.

**Comment by kevinb7** [comment]
Interesting.  I noticed you're implementation was a bit different.  I didn't look at it that closely though.  Infinite ranges seems really useful.
